# Description: This file is used to set config for the attendance app.

welcome_message: ":wave: 出退勤アプリへようこそ"

default_messages:
  begin_office_work: "業務開始します（出社）"
  begin_remote_work: "業務開始します（在宅）"
  finish_work: "業務終了します"
  begin_break_time: "休憩に行ってきます"
  finish_break_time: "休憩から戻りました"

attendance_emoji:
  office_work: ":office:"
  remote_work: ":house:"
  finish_work: ":zzz:"