services:
  slack_attendance_app:
    container_name: slack_attendance_app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./logs:/logs
    ports:
      - "${SLACK_APP_OAUTH_PORT}:80"
    restart: unless-stopped
    depends_on:
      - mysqld

  mysqld:
    container_name: slack_attendance_app_mysqld
    image: mysql:8.4.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: slack_attendance
      MYSQL_USER: slack_attendance
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mysql/slack_attendance_app_mysqld:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    restart: unless-stopped
